DROP TABLE IF EXISTS commodities CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS country_gdp CASCADE;
DROP TABLE IF EXISTS economic_indicators CASCADE;
DROP TABLE IF EXISTS indicators CASCADE;
DROP TABLE IF EXISTS sanctioned_entities CASCADE;
DROP TABLE IF EXISTS sanctions_addresses CASCADE;
DROP TABLE IF EXISTS trade_imports CASCADE;

